language: python
services:
  - docker
python:
  - "3.6"
services:
  - docker
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: pacific-reaches-69261
  api_key: ${HEROKU_API_KEY}
